id = "galib-theme"
name = "Galib Theme"
version = "0.0.1"
schema_version = 1
authors = ["Galib"]
description = "This a soft dark theme for coding"
repository = "https://github.com/galib-savar/Galib-Theme"
